version: "3.9"

services:
  app:
    build:
      context: ./backend-app
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
