apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend-app
spec:
  selector:
    matchLabels:
      app: backend-app #
  replicas: {{ .Values.replicaCount | default 1 }}
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }} #
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URI
          value: {{  (printf "redis://%s-redis-svc:6379" .Release.Name) }}